version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/snippets.json:/usr/src/app/snippets.json
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5175:5173" # frontend available at http://localhost:5175
    volumes:
      - ./frontend:/app
      - /app/node_modules # prevent host node_modules override
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
