version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/snippets.json:/usr/src/app/snippets.json

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
networks:
  default:
    driver: bridge